# DEPRECATED! Moving to Searx for search functionality, instead of homebrewed
# search via my web crawler and a Solr database. This file will probably be
# deleted once Searx is fully implemented.

# Adapted from https://github.com/docker-solr/docker-solr-examples/blob/0e0fd83696d6eb7317b372a34facb06c940c660f/docker-compose/docker-compose.yml
#
# > A docker-compose.yml to start a simple cluster with three ZooKeeper nodes
# > and three Solr nodes.
#
version: '3.7'

services:
  solr1:
    image: solr:8.11.1
    container_name: solr1
    ports:
     - "8983:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2

  solr2:
    image: solr:8.11.1
    container_name: solr2
    ports:
     - "8982:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2

  zoo1:
    image: zookeeper:3.7.0
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
      - 7001:7000
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr

  zoo2:
    image: zookeeper:3.7.0
    container_name: zoo2
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
      - 7002:7000
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr

  redis1:
    image: redis:6.2.6
    container_name: redis1
    restart: always
    hostname: redis1
    ports:
      - 6379:6379

networks:
  solr:
