name: Test and lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  backend:
    name: Run Minitest tests and RuboCop lints

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./backend

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: birdybop
          POSTGRES_PASSWORD: birdybop
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        ruby-version:
          - 2.7.3
          # - 2.6
          # - 2.5

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Ruby v${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      # - name: Create database user
      #   run: createuser -s birdybop

      - name: Set up the database
        run: bundle exec rake db:setup

      - name: Run Minitest tests
        run: bundle exec rails test -cv

      - name: Run RuboCop lints
        run: bundle exec rubocop
